*&---------------------------------------------------------------------*
*& Report ZPB_SALES_ORDER_DISPLAY
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
"LOCAL CLASS IMPLEMENTATION EXAMPLE:
REPORT ZPB_SALES_ORDER_DISPLAY.
"WE HAVE INSTANCE METHOD, SO CREATE OBJECT TO CALL THE CLASS.
"DECLARE OBJECT-->
DATA: LO_OBJECT TYPE REF TO ZUAC_SALES_ORDER_DETAILS.
DATA: LT_FINAL TYPE ZTSTR_SALES_DETAILS_PB.
DATA: LWA_FINAL TYPE ZSTR_SALES_DETAILS_PB.
PARAMETERS: P_VBELN TYPE VBELN_VA.

"CREATE OBJECT-->
CREATE OBJECT LO_OBJECT.
"CALL METHOD-->
CALL METHOD LO_OBJECT->GET_DATA
  EXPORTING
    PVBELN    = P_VBELN
  IMPORTING
    LT_OUTPUT = LT_FINAL
    .
"DISPLAY RESULT-->
LOOP AT LT_FINAL INTO LWA_FINAL.
WRITE: / LWA_FINAL-VBELN, LWA_FINAL-ERDAT, LWA_FINAL-ERZET, LWA_FINAL-ERNAM, LWA_FINAL-POSNR, LWA_FINAL-MATNR.

ENDLOOP.